import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

import { AppSidebar } from "@/components/app-sidebar";
import {
	Breadcrumb,
	BreadcrumbItem,
	BreadcrumbLink,
	BreadcrumbList,
	BreadcrumbPage,
	BreadcrumbSeparator,
} from "@/components/ui/breadcrumb";
import { Separator } from "@/components/ui/separator";
import {
	SidebarInset,
	SidebarProvider,
	SidebarTrigger,
} from "@/components/ui/sidebar";

// const geistSans = Geist({
// 	variable: "--font-geist-sans",
// 	subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
// 	variable: "--font-geist-mono",
// 	subsets: ["latin"],
// });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="dark">
			<body className={`antialiased bg-[var(--mathical-bg)] text-[var(--mathical-text-light)]`}>
				<SidebarProvider>
					<AppSidebar variant="bento" className="border-r-0" />
					<SidebarInset className="relative">
						<header className="bg-transparent absolute top-4 left-4 z-50 flex shrink-0 items-center gap-2">
							<SidebarTrigger className="-ml-1 text-muted-foreground hover:bg-secondary hover:text-white rounded-lg p-2 transition-colors" />
						</header>
						<div className="p-4 md:p-8 pt-16 h-full">
                            {children}
                        </div>
					</SidebarInset>
				</SidebarProvider>
			</body>
		</html>
	);
}
